version: "3"
services:
  web:
    image: hardware-havoc-web
    build: .
    env_file:
      - .env # This file is optional; defaults will be used if it does not exist
    ports:
      - "8405:8405"
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped

  # socketio:
  #   image: hardware-havoc-socket
  #   build:
  #     context: .
  #     dockerfile: socket/dockerfile
  #   ports:
  #     - "8406:8406"

  #   restart: unless-stopped
